// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU0wxtQ1LHfnxB3_YYPDlvQiSRMYz3PJE',
    appId: '1:34953784161:web:c9f13d8d96aae66f8ef320',
    messagingSenderId: '34953784161',
    projectId: 'school-903c8',
    authDomain: 'school-903c8.firebaseapp.com',
    databaseURL: "https://school-903c8-default-rtdb.europe-west1.firebasedatabase.app",
    storageBucket: 'school-903c8.firebasestorage.app',
    measurementId: 'G-MMJH1YMZLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKLEAh-zAwGC7txx8WmlYyUThPCzxjLpA',
    appId: '1:34953784161:android:ed3f11168ead4c138ef320',
    messagingSenderId: '34953784161',
    projectId: 'school-903c8',
    storageBucket: 'school-903c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrGoARuv68pUeCTpu1P3oXjxyHMJJElMk',
    appId: '1:34953784161:ios:8ba39c71a5748caf8ef320',
    messagingSenderId: '34953784161',
    projectId: 'school-903c8',
    storageBucket: 'school-903c8.firebasestorage.app',
    iosBundleId: 'cz.masci.schoolarc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrGoARuv68pUeCTpu1P3oXjxyHMJJElMk',
    appId: '1:34953784161:ios:8ba39c71a5748caf8ef320',
    messagingSenderId: '34953784161',
    projectId: 'school-903c8',
    storageBucket: 'school-903c8.firebasestorage.app',
    iosBundleId: 'cz.masci.schoolarc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU0wxtQ1LHfnxB3_YYPDlvQiSRMYz3PJE',
    appId: '1:34953784161:web:e65fb8dfec47502f8ef320',
    messagingSenderId: '34953784161',
    projectId: 'school-903c8',
    authDomain: 'school-903c8.firebaseapp.com',
    storageBucket: 'school-903c8.firebasestorage.app',
    measurementId: 'G-0HWLMT9D2F',
  );
}
