name: schoolarc
description: "App for students to keep track of their homework and exams"
publish_to: 'none'

version: 2.2.6+66

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  flutter_slidable: ^4.0.3
  dynamic_color: ^1.9.0 #  2.0.0. to 2.1.0 completely broken
  intl: ^0.20.2
  table_calendar: ^3.2.1
  flutter_localizations:
    sdk: flutter
  awesome_notifications_core: ^0.10.1
  awesome_notifications: ^0.12.0
  http: ^1.6.0
  flutter_secure_storage: ^11.0.0
  xml: ^7.0.1
  expandable_page_view: ^1.3.0
  smooth_page_indicator: ^3.0.0
  flutter_resizable_container: ^4.2.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  firebase_database: ^12.4.7
  riverpod: ^3.4.2
  flutter_riverpod: ^3.4.2
  uuid: ^4.5.3
  animated_reorderable_list: ^1.3.0
  home_widget: ^0.9.3
  file_picker: ^12.0.0-beta.4
  async: ^2.13.1
  fl_chart: ^1.2.0
  flutter_svg: ^2.3.0
  m3_expressive_shapes:
    git:
      url: https://github.com/masek-david/m3_expressive_shapes
  m3e_widgets:
    git:
      url: https://github.com/masek-david/m3e_widgets
  url_launcher: ^6.3.2
  device_info_plus: ^13.1.0
  mesh_gradient: ^1.3.8
  material_color_utilities: ^0.13.0
  custom_refresh_indicator: ^4.0.1
  vibration: ^3.2.0
  scrollable_positioned_list: ^0.3.8
  flutter_markdown_plus: ^1.0.7
  web: ^1.1.1
  yaml: ^3.1.3
  web_haptics: ^0.0.2
  pretty_qr_code: ^3.6.0
  share_plus: ^13.3.0
  app_links: ^7.2.1
  cbor: ^6.5.1
  posthog_flutter: ^5.36.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.15.0
  hive_ce_generator: ^1.11.2
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - pubspec.yaml
    - assets/changelog.md
    - assets/book.svg
    - assets/pen.svg
    - assets/confetti.svg
    - assets/schoolarc_logo.svg
    - assets/schoolarc_icon.svg
    - assets/images/android_notification_light.webp
    - assets/images/android_notification_dark.webp
    - assets/images/android_widgets_light.webp
    - assets/images/android_widgets_dark.webp

  fonts:
    - family: Roboto Serif
      fonts:
        - asset: assets/fonts/RobotoSerif-VariableFont_GRAD,opsz,wdth,wght.ttf
    - family: Google Sans Flex
      fonts:
        - asset: assets\fonts\GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf
