name: schoolarc
description: "Simple app for students to take track of their homeworks and exams"
publish_to: 'none'

version: 2.2.3+56

environment:
  sdk: '>=3.10.0 <4.0.0'

dependency_overrides:
  # flutter_localizations needs 1.19 but awesome_notifications 0.10.1 (i need this for flutter 3.29.0) need 1.20
  intl: any
  # flutter uses some older version, like 0.11.2, but i want to use latest
  material_color_utilities: ^0.13.0

dependencies:
  flutter:
    sdk: flutter

  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  flutter_slidable: ^4.0.3
  dynamic_color: ^1.8.1
  intl: any
  table_calendar: ^3.2.0
  flutter_localizations:
    sdk: flutter
  awesome_notifications_core: ^0.10.1
  awesome_notifications: ^0.11.0
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  xml: 6.6.1
  expandable_page_view: ^1.3.0
  smooth_page_indicator: ^2.0.1
  flutter_resizable_container: ^4.2.0
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  firebase_database: ^12.3.0
  riverpod: ^3.2.1
  flutter_riverpod: ^3.3.1
  uuid: ^4.5.3
  animated_reorderable_list: ^1.3.0
  home_widget: ^0.9.1
  file_picker: ^11.0.2
  async: ^2.13.1
  fl_chart: ^1.2.0
  flutter_svg: ^2.2.4
  m3_expressive_shapes:
    git:
      url: https://github.com/masek-david/m3_expressive_shapes
  url_launcher: ^6.3.2
  device_info_plus: ^12.4.0
  mesh_gradient: ^1.3.8
  material_color_utilities: ^0.13.0
  workmanager: ^0.9.0+3
  custom_refresh_indicator: ^4.0.1
  vibration: ^3.1.8
  scrollable_positioned_list: ^0.3.8
  flutter_markdown_plus: ^1.0.7
  markdown: ^7.3.1
  web: ^1.1.1
  yaml: ^3.1.3
  web_haptics: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.15.0
  hive_ce_generator: ^1.11.1
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - pubspec.yaml
    - assets/changelog.md
    - assets/book.svg
    - assets/pen.svg
    - assets/confetti.svg
    - assets/schoolarc_logo.svg
    - assets/schoolarc_icon.svg
    - assets/images/android_notification_light.webp
    - assets/images/android_notification_dark.webp
    - assets/images/android_widgets_light.webp
    - assets/images/android_widgets_dark.webp

  fonts:
    - family: Roboto Serif
      fonts:
        - asset: assets/fonts/RobotoSerif-VariableFont_GRAD,opsz,wdth,wght.ttf
    - family: Google Sans Flex
      fonts:
        - asset: assets\fonts\GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf
