// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:schoolarc/database/hive/hive_adapters.dart';
import 'package:schoolarc/models/date/date.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DateAdapter());
    registerAdapter(ExamEntityAdapter());
    registerAdapter(HomeworkEntityAdapter());
    registerAdapter(LessonEntityAdapter());
    registerAdapter(LogAdapter());
    registerAdapter(PeriodAdapter());
    registerAdapter(SubjectEntityAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(TimetableEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DateAdapter());
    registerAdapter(ExamEntityAdapter());
    registerAdapter(HomeworkEntityAdapter());
    registerAdapter(LessonEntityAdapter());
    registerAdapter(LogAdapter());
    registerAdapter(PeriodAdapter());
    registerAdapter(SubjectEntityAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(TimetableEntityAdapter());
  }
}
