allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

val newBuildDir: Directory =
    rootProject.layout.buildDirectory
        .dir("../../build")
        .get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    val newSubprojectBuildDir: Directory = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}
subprojects {
    project.evaluationDependsOn(":app")
    
    // --- FLUTTER PLUGIN SDK OVERRIDE --- generated by Gemini
    // Forces all third-party Flutter plugins (subprojects) to compile against SDK 37.
    // Workaround for older plugins (e.g., awesome_notifications_core) that hardcode lower
    // compileSdk versions (like 33). This prevents release build crashes during the 
    // 'checkReleaseAarMetadata' task, which happens because newer AndroidX libraries demand SDK 34+.
    // Safe to keep permanently, or can be removed once all pubspec dependencies natively target SDK 34+.
    subprojects {
        if (project.state.executed) {
            if (project.plugins.hasPlugin("com.android.library")) {
                project.extensions.configure<com.android.build.gradle.LibraryExtension>("android") {
                    compileSdk = 37
                }
            }
        } else {
            project.afterEvaluate {
                if (project.plugins.hasPlugin("com.android.library")) {
                    project.extensions.configure<com.android.build.gradle.LibraryExtension>("android") {
                        compileSdk = 37
                    }
                }
            }
        }
    }
}

tasks.register<Delete>("clean") {
    delete(rootProject.buildDir)
}
