# Define the iOS platform version for your project
platform :ios, '12.0'

# This line is required to load Flutter-specific configurations
load File.expand_path('flutter', __dir__)
target 'Runner' do
  # Use dynamic frameworks for the project
  use_frameworks!
  use_modular_headers!
  # Integrate Flutter pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  # Add test target if needed
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
  
    ################  Awesome Notifications pod modification  ###################
    awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
    require awesome_pod_file
    update_awesome_pod_build_settings(installer)
    ################  Awesome Notifications pod modification  ###################
  end
    
  ################  Awesome Notifications pod modification  ###################
  awesome_pod_file = File.expand_path(File.join('plugins', 'awesome_notifications', 'ios', 'Scripts', 'AwesomePodFile'), '.symlinks')
  require awesome_pod_file
  update_awesome_main_target_settings('Runner', File.dirname(File.realpath(__FILE__)), flutter_root)
  ################  Awesome Notifications pod modification  ###################