// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:school_manager/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    if (!Hive.isAdapterRegistered(ExamAdapter().typeId)) {
      Hive.registerAdapter(ExamAdapter());
    }
    if (!Hive.isAdapterRegistered(HomeworkAdapter().typeId)) {
      Hive.registerAdapter(HomeworkAdapter());
    }
    if (!Hive.isAdapterRegistered(LessonTimesAdapter().typeId)) {
      Hive.registerAdapter(LessonTimesAdapter());
    }
    if (!Hive.isAdapterRegistered(LogAdapter().typeId)) {
      Hive.registerAdapter(LogAdapter());
    }
    if (!Hive.isAdapterRegistered(SubjectAdapter().typeId)) {
      Hive.registerAdapter(SubjectAdapter());
    }
    if (!Hive.isAdapterRegistered(TimeTableAdapter().typeId)) {
      Hive.registerAdapter(TimeTableAdapter());
    }
  }
}
